pipeline {
    agent any
    stages {
        stage('Create File') {
            steps {
                sh 'echo "This is a test file" > testfile.txt'
            }
        }
        stage('Read File') {
            steps {
                sh 'cat testfile.txt'
            }
        }
        stage('Delete File') {
            steps {
                sh 'rm testfile.txt'
            }
        }
    }
}
