pipeline {
    agent any
    stages {
        stage('Check PATH') {
            steps {
                sh 'echo $PATH'
            }
        }
        stage('Test Docker') {
            steps {
                sh 'docker --version'
            }
        }
    }
}
